### ISSUE TITLE
Add mp_rand_interval function?

### ISSUE THREAD

**Issue by minad** [libtom/libtommath#237]
* For testing this is bad since we are using mp_rand there and don't cover the full interval due to that peculiar behavior of mp_rand.

* For cryptographical use it might make a difference?

See #236

**Comment by sjaeckel** [comment]
> > My tendency goes btw. to use rand_bn_bits() allover LTC and to remove mp_rand() from the imported API resp. not use it anymore.
> 
> Yes I think LTC should generate its own random numbers. This way you can control very tightly want your cryptographical requirements are.

I had again a look at it and then I remembered why it uses `mp_rand()` ... there's no prng context available and IIRC the random number for the blinding value doesn't have to be cryptographically secure (please correct me if I'm wrong!)

**Comment by minad** [comment]
> there's no prng context available

What do you mean by that? mp_rand also uses an ambient prng context provided by the OS. Assuming that you would want to break the dependency to ltm for example, is it not possible to just copy mp_rand over?

**Comment by sjaeckel** [comment]
> > there's no prng context available
> 
> What do you mean by that? mp_rand also uses an ambient prng context provided by the OS. Assuming that you would want to break the dependency to ltm for example, is it not possible to just copy mp_rand over?

all functionality in ltc that requires reading from a (p)rng has a prng-context as parameter, to be able to pass one of the supplied prng implementations instead of a system-specific rng (which is not always available).

When we introduced this dependency, instead of fixing this by giving the context as parameter, we simply delegated it downwards to the math library which is now biting us, but which is no problem as we're going to break API and ABI for the next ltc release anyway.

**Comment by minad** [comment]
Keep things as is.
