### ISSUE TITLE
mistake in mp_div

### ISSUE THREAD

**Issue by dmitry-lipetsk** [libtom/libtommath#68]
In code:
```
  /* step 3. for i from n down to (t + 1) */
  for (i = n; i >= (t + 1); i--) {
    if (i > x.used) {
      continue;
    }
```

I think, should be:
```
   if (i >= x.used) {
```

Decimal numbers (radix==10) for test operation (a / b):

a=3067161331641079976151533586319557730249073818741761610008250427475901610199879968766329531563687043693402621268943124868381696242108642234231961730721843589353846747206472781244530543373423697860384124350169319274508178224664556550535653424037901850281783620936151120511351560268242242944861690615059558257179150439309203196444289158574162364448252611588808917477886531318273928442271549262235942891697671710701430134360572789944439609882091248919666254084798263561644567930542524789226705258184111355143245563109214371174898026588545768462834262830136558105821577991371394478637020935897350920595595149428868836454

b=161854874649776085868045952190159031555772097014435707776279513538616175047026058065927714606879676219064271341818754038806823814541886861147177045257236811627035155212310813305487929926508522581710604504792711726648563877865328333166885998671854094528177699206377434633696300213499023964016345755132798642663

The problem occurred at line
```
  /* step 3.1 if xi == yt then set q{i-t-1} to b-1,
   * otherwise set q{i-t-1} to (xi*b + x{i-1})/yt */
  if(x.dp[i] == y.dp[t])  //<---------------------- HERE. i==52, x.used==52
```

**Comment by czurnieden** [comment]
Hi Dmitry,

was not able to repeat that error with a normal 64-bit pc.

Would you mind to give us a bit more information? What is your result, the version of libtommath, which OS on which architecture with which compiler?

Christoph Zurnieden

**Comment by dmitry-lipetsk** [comment]
Hi

Win10 x64, VS2015 SP3

my clone of libtommath (exact source code) - https://github.com/dmitry-lipetsk/libtommath-for-ibprovider--set01
based on - https://github.com/FirebirdSQL/firebird/tree/master/extern/libtommath

My result - "out of range" error. Valid range: [0...x.used)

In other case, as I understand, you can get the incorrect result of mp_div or AV.

Dmitry Kovalenko

**Comment by czurnieden** [comment]
You do not only want support for a C++ port instead of the original C-code from https://github.com/libtom/libtommath, you also had ported LibTomMath code that was not original in the first place and it is not repeatable with the current version of LibTomMath.

Not a bug.

**Comment by dmitry-lipetsk** [comment]
:FACEPALM:

**Comment by czurnieden** [comment]
Several different versions LibTomMath get used in several dozen different applications. Do you want us to support every one of those versions? It is quite normal in any development open to public comments that only the current version(s) get support.

So if you can repeat your problem in the current version and describe your method in such a way and form that others can repeat your test *and* find the described bug I will <del>happily</del> reopen this issue.

And recall over one hundred sensor packets where I used LibTomMath to implement rational math in a small MCU. So rest assured that will not take any errors in LibTomMath easily because wrong results will cost me much more than just the recall.

**Comment by dmitry-lipetsk** [comment]
It was incorrect offer :(

Access after end element - it is mp_div behavior "by design".

For avoid a read after last element ( x.dp[x.used] ) need use other solution.
