### ISSUE TITLE
 '__int128' keyword not supported on this architecture x64	libtommath

### ISSUE THREAD

**Issue by shaildev123** [libtom/libtommath#99]
Hi,

Can you please tell me any quick fix for this?

Regards
Shail

**Comment by sjaeckel** [comment]
Can you please give more details about the issue? Such as the compiler used, the architecture to build for and building on and the version of the library.

**Comment by shaildev123** [comment]
I am using libtommath v1. 0.1 and libtomcrypt v1. 18.0

Windows compiler msvc12. 0-64
Architecture. x64



On Jan 4, 2018 7:33 PM, "Steffen Jaeckel" <notifications@github.com> wrote:

Can you please give more details about the issue? Such as the compiler
used, the architecture to build for and building on and the version of the
library.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/libtom/libtommath/issues/99#issuecomment-355289604>,
or mute
the thread

**Comment by sjaeckel** [comment]
As found out [here](https://github.com/libtom/libtomcrypt/issues/306#issuecomment-333765095) msvc has no support for 128-bit integer types and therefore you have to define `MP_32BIT`. The latest [`develop` branch](https://github.com/libtom/libtommath/tree/develop) still needs to be released, but there are fixes for even more issues on msvc in #91 
So please use the sources from the latest develop branch instead of the last release or apply the changes of #91 to your sources.
